version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: trello_postgres
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    ports:
      - "9983:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: