name: Node.js CI

on:
  push:
    branches: ["feat/setup-cicd"]
  pull_request:
    branches: ["feat/setup-cicd"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Specify the major version
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
