import {
  EnumCustomFieldSource,
  EnumCustomFieldType,
} from "@/types/custom_field";
import type { QueryInterface } from "sequelize";

type OptionItem = {
  label: string;
  value: string;
};

type CustomField = {
  id: string;
  name: string;
  type: EnumCustomFieldType;
  is_show_at_front: boolean;
  options?: OptionItem[];
  order: number;
  description: string;
  workspace_id: string;
  can_view?: string[];
  can_edit?: string[];
};

const CUSTOM_FIELD_IDS = {
  // Design Process Fields
  CABANG: "8fce8a0b-5a47-4bc5-a2de-c9a0d3e47e47",
  DEAL_MAKER: "2a42b7c2-33f1-468f-8fa6-6a2f3cd09888",
  DESAIN_LANGSUNG: "f3e679d2-bcc3-4f68-a9c4-1aaf40c92694",
  PRODUK: "f64332ee-5e93-4ac5-a64a-e5d419083ac5",
  VARIAN: "6b8d46f0-94f7-48f3-9319-f1660e93c2d6",
  JENIS_CETAK: "e5be3038-8c45-4c4e-a008-893902c78ae5",
  BAHAN: "cf899f44-9b2c-4f84-a041-bd1818ac62f3",
  WARNA: "2d5cb9c6-6353-474a-8fcf-63a8ea60d268",
  DESAINER: "25de8012-bccc-4f60-bf6d-963d1c53a8f2",
  TERKIRIM_DM: "63a5ef3e-69be-4d11-85f4-8ce10ac1d3f3",
  TERKIRIM_KONSUMEN: "a9f80358-50b1-4f7d-8179-6fbe4b9d98ea",
  REVISI_DESAIN: "ea8753c5-2073-4c21-81f3-9483654d3084",
  DESAIN_ACC: "e1df1ad7-dfb9-4d7a-9b6e-1f99c5367770",

  // Order Information Fields
  PRIORITAS: "708d4b58-b780-4b0a-bd2d-baf8dc8b0c8f",
  NO_FAKTUR: "6c7f05f1-85bc-42f3-98b2-6a6509cc539c",
  JML_PESANAN: "7bd961d5-019e-408f-9b40-2be7b8a0e15b",
  CUSTOMER: "a8df9c58-3a61-43ad-804a-6bc37c28a703",
  REPEAT: "ab274d96-9c7c-463e-8fd3-2f24845b4797",
  EKSPEDISI: "137a6797-186c-4a77-b12f-1a40fcdbfe74",

  // Delivery Fields
  NO_PTT: "3a2036cf-24c4-4aa9-87eb-7e40233d3c4f",
  DITERIMA_OUTLET: "7cc38cfd-245c-4ea2-b92b-9cd7e6a2719c",
  DITERIMA_KONSUMEN: "db2127a5-1246-4f42-a265-79ac34e40c12",

  // PPIC Fields
  VARIASI_POLA: "fbb4b25e-2c18-4e1b-a496-3c00a0ad535b",
  BELI_BAHAN: "4497791a-1427-4c41-9df4-1161167632b9",
  JENIS_CETAK_PPIC: "9d924231-1b3a-43b5-9bbf-6a901c99a260",

  // Warehouse Produk Fields
  READY_STOK: "b1bbac7f-8964-4b89-8bb9-442e7c9d9437",
  PO_PELENGKAP: "c49c96e2-d61d-44b3-83b4-d29b70ae5ad3",
  OBRAS_SAKU: "b2345678-9abc-def1-2345-6789abcdef12",

  // Warehouse Bahan Fields
  BAHAN_TERLOADING: "bb14e8c5-0051-4c0d-9c2c-f26f6c8aa748",
  LOADING: "ed207a61-1a37-465e-947e-637f29e7891e",

  // Cutting Fields
  BAHAN_TERPAKAI: "df87fc2a-9e2a-4b2c-aeae-3e2d1a6fa119",
  CUTTING: "0a3939d6-3173-4641-a479-cf85a7c63560",

  // Production Line Fields
  NUMBERING: "35e3fd88-0de5-4389-a7e1-58981a0c5113",
  LOADING_LINE: "dbe6315a-660f-4041-9f58-c747e1b7c831",
  SEWING: "43100f27-982f-4fd6-b346-f95ff39bc8ff",
  QC: "ef13f8d4-d964-40cd-9297-4a9295357b59",

  // Bordir Fields
  MESIN_BORDIR: "2e4968b1-60b6-47b3-a998-f4a2194041c6",
  SIAP_BORDIR: "aeaa84e2-d869-4145-8be7-5cc9738bc4d0",
  LOADING_BORDIR: "8c269b9f-d248-4903-bb76-b49f5cd6cb82",
  BORDIR: "4f02a5aa-1a40-4ac0-bd96-7a473bf69d5a",
  DTF_SABLON: "49d1e2b8-8677-4ce8-b245-3a11e30b05db",

  // Final Process Fields
  PACKING: "a8f16345-ff20-4c5f-a3a4-c8ce8e23621c",
  DELIVERY: "c4be4f3c-3a06-4c48-94bc-038e7791a1b5",

  // Production Details
  PRODUKSI: "bd3c1d42-9d87-41b7-b3ef-cf6e7c6f4b36",
  JML_PRODUKSI: "10ebff75-62fa-41a4-b99d-0ce4b8d36890",

  // Bordir Design Fields
  DESAINER_BORDIR: "98bc4ce5-3430-49a0-92d0-008b85a4581b",
  CEK_DESAIN_BORDIR: "a90503d2-ff38-45e6-8a5d-b593e90e3c8f",
  JML_STITCH: "a02e6e0e-49b8-4722-a04c-fc4a1087a725",

  // Date Fields
  WAKTU_LOADING: "87ec3e3d-6b6e-43fc-a0f0-9ea3d7ea8bce",
  SELESAI_CUTTING: "911a2e6b-336e-4e67-9f4a-cb10f7cfae3d",
  WAKTU_LOADING_LINE: "b730e3c5-5baf-474d-bd4b-f2638e0b74a2",
  SELESAI_SEWING: "fca53c6b-b173-4dd4-9fa7-4fbd8b1f2e00",
  SELESAI_QC: "45243f6f-ea88-4712-a321-44183f32152e",
  WAKTU_SIAP_BORDIR: "8b9c217b-d3b4-45c0-a70f-24618d795055",
  SELESAI_BORDIR: "4f4113b6-c60a-4d4e-9a57-cabaf9a6a651",
  SELESAI_DTF: "ae6f5213-0b8f-498b-8590-7e2a8a0c8ec4",
  SELESAI_PACKING: "eec578a4-3e91-41e6-b73b-906cd39854c0",
  TGL_SELESAI: "aa2e5cb6-0602-4f78-bc88-47d0d527c80e",

  // Purchasing - Material Fields
  SUPPLIER_BAHAN: "c6f849f5-c452-4690-beb3-1117d12b9c84",
  JENIS_BAHAN: "212c8c4c-efc1-49c4-8679-342d4be61eb5",
  WARNA_KAIN: "9d3d182b-d612-43d9-bbe1-d03222a62026",
  JML_ROLL: "0a202fc6-d3a0-4b0e-ade1-832e2fbc177c",
  JUMLAH_KM: "22732e11-bd1c-47f7-993c-33ab6356ae94",
  JUMLAH_RIB: "2f0d2343-dafe-455d-b5a2-f0be41ffb1c4",
  QTY_BELI_KAIN: "6f4dc4a4-2c91-404c-832e-d40bb52e87b3",
  JENIS_JAHITAN: "e4f9ea1d-fb36-41fd-9876-64b243dd799c",
  TGL_DITERIMA: "9488cc16-8c32-4c38-94b0-36cd4f2c3972",

  // Purchasing - Suppliers
  SUPPLIER_KM_CUSTOM: "f6010b36-29aa-49de-8fd1-8cdd65de1972",
  SUPPLIER_ACC: "0c5ae297-f0c5-4062-8e0d-f978fd5de149",
  SUPPLIER_SPAREPART: "5dbd4ce6-3a38-42b1-ae6e-d2c8ebf2aa0a",
  SUPPLIER_PERLENGKAPAN: "36723c69-98ed-45bc-8a76-d8f0a7bcaf3d",

  // Delivery Management
  ASAL: "67df7699-7c69-4232-a0b0-20ae17b1ad57",
  TUJUAN: "d957f2a9-b3f7-476c-b9d9-b37f9c58732e",
  KURIR: "7169f84d-b0e3-474f-8476-ff72c3bb9462",

  // Operator Bordir Fields
  OPERATOR: "ec0b2cc3-67e0-4e0c-a849-10e4a89e4cb6",
  NAMA_CUSTOMER_OPERATOR: "0844292b-1767-4326-b746-c3bb128ab62d",
  MESIN_BORDIR_OPERATOR: "56a7e6ab-f8f0-4ad0-ae11-ff99ed1edbce",
  JENIS_ORDER: "6746ec7c-2890-4f2a-9674-c2e5b9937f6e",
  NAMA_FILE: "3c6d18a3-2d6e-4a91-8e82-c96167810351",
  DESAINER_OPERATOR: "b2781af5-c209-4dc1-9f63-9a0e3d0085dc",
  STITCH: "d25a1738-2e2b-4ff4-9a7e-6822584fc694",
  JUMLAH_BORDIR: "fd53072b-73a2-49e6-87f5-88409d3f1486",
  TOTAL_STITCH: "0d208f0a-48d0-4a6f-9b55-160249801c86",

  // Finishing Bordir Fields
  FINISHER: "2ea42167-3f94-4498-9b07-df7b78cfb938",
  NAMA_CUSTOMER_FINISHING: "2a5de239-8d26-4d6a-9c3e-1c265157b5d2",
  NAMA_FILE_FINISHING: "f3d4d4f6-f019-462f-a72a-3cc4fffc3fdf",
  JUMLAH_BORDIR_FINISHING: "f9336e07-0fa1-43cc-860d-c62137e6c8b7",
} as const;

const WORKSPACE_ID = "eb65c15c-12cc-49e4-9827-16ef1c838c4d";

// Helper function to create options
const createOptions = (values: string[]): OptionItem[] =>
  values.map((value) => ({ label: value, value }));

const customFields: CustomField[] = [
  // Design Process Fields (1-13)
  {
    id: CUSTOM_FIELD_IDS.CABANG,
    name: "Cabang",
    type: EnumCustomFieldType.Dropdown,
    is_show_at_front: true,
    options: createOptions([
      "WBT",
      "KBT",
      "KLT",
      "MGW",
      "SLO",
      "IND",
      "PLO",
      "BRD",
    ]),
    order: 1,
    description:
      "isi manual oleh deal maker / otomatis terisi dari Accurate (diambil dari kode nomor faktur)",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.DEAL_MAKER,
    name: "Deal Maker",
    type: EnumCustomFieldType.Dropdown,
    is_show_at_front: true,
    options: createOptions([
      "Clariesta Dinar Ariela",
      "Cicilia Siannawati",
      "Debby Angelina",
      "Devi Sofiana",
      "Hari Sucipto",
      "Lenni Luvita Dewi",
      "Ramli Ramadhan",
      "Reni",
      "Uswatun Hasanah",
      "Yudo Hadianto",
    ]),
    order: 2,
    description:
      "List nama HARUS MATCH dengan nama penjual di Accurate / otomatis terisi dari Accurate (penjual)",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.DESAIN_LANGSUNG,
    name: "Desain Langsung",
    type: EnumCustomFieldType.Dropdown,
    is_show_at_front: true,
    options: createOptions(["Ya", "Tidak"]),
    order: 3,
    description: "isi manual oleh deal maker",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.PRODUK,
    name: "Produk",
    type: EnumCustomFieldType.Dropdown,
    is_show_at_front: true,
    options: createOptions([
      "HEMCA Polo",
      "HEMCA Oblong",
      "Custom Polo",
      "Custom Oblong",
      "Custom Kemeja",
      "Custom Jaket",
      "Custom Rompi",
      "Custom Celana",
      "Custom Alamamater",
      "Custom Topi",
      "Custom Jersey",
      "Custom Apron",
      "Custom Bordir",
    ]),
    order: 4,
    description:
      "List produk HARUS MATCH dengan di Accurate / otomatis terisi dari Accurate (charfield7)",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.VARIAN,
    name: "Varian",
    type: EnumCustomFieldType.Dropdown,
    is_show_at_front: true,
    options: createOptions(["Polos", "KMB"]),
    order: 5,
    description:
      "isi manual oleh deal maker / isi manual oleh Warehouse bahan / isi manual oleh purchasing",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.JENIS_CETAK,
    name: "Jenis Cetak",
    type: EnumCustomFieldType.Dropdown,
    is_show_at_front: true,
    options: createOptions(["Bordir", "DTF", "Plastisol", "Rubber"]),
    order: 6,
    description: "isi manual oleh deal maker",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.BAHAN,
    name: "Bahan",
    type: EnumCustomFieldType.Dropdown,
    is_show_at_front: true,
    options: createOptions([
      "Lacost Pique Soft 20s",
      "Lacost CVC 20s",
      "Lacost CVC 24s",
      "Cotton Combed 20s",
      "Cotton Combed 24s",
      "Cotton Combed 30s",
      "American Drill",
      "Nagata Drill",
      "Oxford",
      "Textmoda",
      "Ribstop",
      "Taslan Milky",
      "Micro",
      "Adidas",
      "Lotto",
      "Diadora",
      "Canvas Marsoto",
      "Cotton Fleece",
      "PE Fleece",
    ]),
    order: 7,
    description: "di isi manual oleh deal maker",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.WARNA,
    name: "Warna",
    type: EnumCustomFieldType.Dropdown,
    is_show_at_front: true,
    options: [],
    order: 8,
    description:
      "database warna diambil dari bahan / isi manual oleh Warehouse bahan (besok otomatis by scan barcode)",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.DESAINER,
    name: "Desainer",
    type: EnumCustomFieldType.Dropdown,
    is_show_at_front: true,
    options: createOptions(["Fananda", "Raka", "Ridwan", "Tyo", "Winner"]),
    order: 9,
    description: "isi manual oleh desainer outlet",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.TERKIRIM_DM,
    name: "Terkirim ke DM",
    type: EnumCustomFieldType.Checkbox,
    is_show_at_front: true,
    order: 10,
    description: "dicentang oleh desainer outlet",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.TERKIRIM_KONSUMEN,
    name: "Terkirim ke Konsumen",
    type: EnumCustomFieldType.Checkbox,
    is_show_at_front: true,
    order: 11,
    description: "dicentang oleh deal maker",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.REVISI_DESAIN,
    name: "Revisi Desain",
    type: EnumCustomFieldType.Checkbox,
    is_show_at_front: true,
    order: 12,
    description: "dicentang oleh deal maker",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.DESAIN_ACC,
    name: "Desain ACC",
    type: EnumCustomFieldType.Checkbox,
    is_show_at_front: true,
    order: 13,
    description: "dicentang oleh deal maker",
    workspace_id: WORKSPACE_ID,
  },

  // Order Information Fields (14-19)
  {
    id: CUSTOM_FIELD_IDS.PRIORITAS,
    name: "Prioritas",
    type: EnumCustomFieldType.Dropdown,
    is_show_at_front: true,
    options: createOptions(["Express"]),
    order: 14,
    description: "otomatis terisi dari Accurate Charfield6",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.NO_FAKTUR,
    name: "No Faktur",
    type: EnumCustomFieldType.Text,
    is_show_at_front: true,
    order: 15,
    description: "otomatis terisi dari Accurate",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.JML_PESANAN,
    name: "Jml Pesanan",
    type: EnumCustomFieldType.Number,
    is_show_at_front: true,
    order: 16,
    description: "otomatis terisi dari Accurate",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.CUSTOMER,
    name: "Customer",
    type: EnumCustomFieldType.Text,
    is_show_at_front: true,
    order: 17,
    description: "otomatis terisi dari Accurate (pelanggan)",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.REPEAT,
    name: "Repeat",
    type: EnumCustomFieldType.Dropdown,
    is_show_at_front: true,
    options: createOptions(["Ya", "Tidak"]),
    order: 18,
    description: "otomatis terisi dari Accurate (charfield2)",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.EKSPEDISI,
    name: "Ekspedisi",
    type: EnumCustomFieldType.Dropdown,
    is_show_at_front: true,
    options: [],
    order: 19,
    description: "otomatis terisi dari Accurate (pengiriman)",
    workspace_id: WORKSPACE_ID,
  },

  // Delivery Fields (20-22)
  {
    id: CUSTOM_FIELD_IDS.NO_PTT,
    name: "No PTT",
    type: EnumCustomFieldType.Number,
    is_show_at_front: true,
    order: 20,
    description: "Custom field dari Delivery / isi manual oleh PA outlet",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.DITERIMA_OUTLET,
    name: "Diterima Outlet",
    type: EnumCustomFieldType.Checkbox,
    is_show_at_front: true,
    order: 21,
    description: "Custom field dari Delivery / centang manual oleh PA Outlet",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.DITERIMA_KONSUMEN,
    name: "Diterima Konsumen",
    type: EnumCustomFieldType.Checkbox,
    is_show_at_front: true,
    order: 22,
    description:
      "otomatis tercentang ketika upload bukti pengambilan / pengiriman oleh Deal Maker / centang manual oleh kurir (jika barang langsung ke konsumen)",
    workspace_id: WORKSPACE_ID,
  },

  // PPIC Fields (23-25)
  {
    id: CUSTOM_FIELD_IDS.VARIASI_POLA,
    name: "Variasi Pola",
    type: EnumCustomFieldType.Dropdown,
    is_show_at_front: true,
    options: createOptions(["Ya", "Tidak"]),
    order: 23,
    description: "isi manual oleh PPIC",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.BELI_BAHAN,
    name: "Beli Bahan",
    type: EnumCustomFieldType.Dropdown,
    is_show_at_front: true,
    options: createOptions(["Ya", "Tidak"]),
    order: 24,
    description: "isi manual oleh PPIC",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.JENIS_CETAK_PPIC,
    name: "Jenis Cetak PPIC",
    type: EnumCustomFieldType.Dropdown,
    is_show_at_front: true,
    options: createOptions([
      "Bordir",
      "DTF",
      "Sablon",
      "Polosan",
      "Bordir & DTF",
      "Bordir & Sablon",
    ]),
    order: 25,
    description: "isi manual oleh PPIC",
    workspace_id: WORKSPACE_ID,
  },

  // Warehouse Produk Fields (26-28)
  {
    id: CUSTOM_FIELD_IDS.READY_STOK,
    name: "Ready Stok",
    type: EnumCustomFieldType.Dropdown,
    is_show_at_front: true,
    options: createOptions(["Full Stok", "Sebagian Bikin", "Bikin Semua"]),
    order: 26,
    description: "isi manual oleh Warehouse Produk",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.PO_PELENGKAP,
    name: "PO Pelengkap",
    type: EnumCustomFieldType.Dropdown,
    is_show_at_front: true,
    options: createOptions(["Ya", "Tidak"]),
    order: 27,
    description: "isi manual oleh Warehouse Produk",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.OBRAS_SAKU,
    name: "Obras/Saku",
    type: EnumCustomFieldType.Dropdown,
    is_show_at_front: true,
    options: createOptions(["Ya", "Tidak"]),
    order: 28,
    description: "isi manual oleh Warehouse Produk",
    workspace_id: WORKSPACE_ID,
  },

  // Warehouse Bahan Fields (29-30)
  {
    id: CUSTOM_FIELD_IDS.BAHAN_TERLOADING,
    name: "Bahan Terloading (kg/m)",
    type: EnumCustomFieldType.Number,
    is_show_at_front: true,
    order: 29,
    description: "isi manual oleh Warehouse Bahan",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.LOADING,
    name: "Loading",
    type: EnumCustomFieldType.Checkbox,
    is_show_at_front: true,
    order: 30,
    description: "otomatis tercentang setelah bahan terloading terisi",
    workspace_id: WORKSPACE_ID,
  },

  // Cutting Fields (31-32)
  {
    id: CUSTOM_FIELD_IDS.BAHAN_TERPAKAI,
    name: "Bahan Terpakai (kg/m)",
    type: EnumCustomFieldType.Number,
    is_show_at_front: true,
    order: 31,
    description: "isi manual oleh Cutting",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.CUTTING,
    name: "Cutting",
    type: EnumCustomFieldType.Checkbox,
    is_show_at_front: true,
    order: 32,
    description: "otomatis tercentang setelah bahan terpakai terisi",
    workspace_id: WORKSPACE_ID,
  },

  // Production Line Fields (33-36)
  {
    id: CUSTOM_FIELD_IDS.NUMBERING,
    name: "Numbering",
    type: EnumCustomFieldType.Checkbox,
    is_show_at_front: true,
    order: 33,
    description: "centang oleh Numbering",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.LOADING_LINE,
    name: "Loading Line",
    type: EnumCustomFieldType.Checkbox,
    is_show_at_front: true,
    order: 34,
    description: "centang oleh Helper Line",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.SEWING,
    name: "Sewing",
    type: EnumCustomFieldType.Checkbox,
    is_show_at_front: true,
    order: 35,
    description: "centang oleh SPV Sewing",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.QC,
    name: "QC",
    type: EnumCustomFieldType.Checkbox,
    is_show_at_front: true,
    order: 36,
    description: "centang oleh QC",
    workspace_id: WORKSPACE_ID,
  },

  // Bordir Fields (37-41)
  {
    id: CUSTOM_FIELD_IDS.MESIN_BORDIR,
    name: "Mesin Bordir",
    type: EnumCustomFieldType.Dropdown,
    is_show_at_front: true,
    options: createOptions([
      "6 Head | PBR",
      "12 Head | PBR",
      "4 Head | SLO",
      "2 Head | WBT",
      "DTF / Sablon",
      "Polosan",
    ]),
    order: 37,
    description: "isi manual oleh SPV Operator Bordir",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.SIAP_BORDIR,
    name: "Siap Bordir",
    type: EnumCustomFieldType.Checkbox,
    is_show_at_front: true,
    order: 38,
    description: "centang oleh finishing packing",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.LOADING_BORDIR,
    name: "Loading Bordir",
    type: EnumCustomFieldType.Checkbox,
    is_show_at_front: true,
    order: 39,
    description: "centang oleh SPV Operator Bordir",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.BORDIR,
    name: "Bordir",
    type: EnumCustomFieldType.Checkbox,
    is_show_at_front: true,
    order: 40,
    description:
      "centang oleh finishing bordir (nanti dibuat otomatis ketika jml stitch = 0)",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.DTF_SABLON,
    name: "DTF / Sablon",
    type: EnumCustomFieldType.Checkbox,
    is_show_at_front: true,
    order: 41,
    description: "centang oleh operator sablon",
    workspace_id: WORKSPACE_ID,
  },

  // Final Process Fields (42-43)
  {
    id: CUSTOM_FIELD_IDS.PACKING,
    name: "Packing",
    type: EnumCustomFieldType.Checkbox,
    is_show_at_front: true,
    order: 42,
    description: "centang oleh finishing packing",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.DELIVERY,
    name: "Delivery",
    type: EnumCustomFieldType.Checkbox,
    is_show_at_front: true,
    order: 43,
    description: "centang oleh spv kurir",
    workspace_id: WORKSPACE_ID,
  },

  // Production Details (44-45)
  {
    id: CUSTOM_FIELD_IDS.PRODUKSI,
    name: "Produksi",
    type: EnumCustomFieldType.Dropdown,
    is_show_at_front: true,
    options: createOptions(["Line 4", "Line 5", "Line 6", "Borongan"]),
    order: 44,
    description: "isi manual oleh SPV Sewing",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.JML_PRODUKSI,
    name: "Jml Produksi",
    type: EnumCustomFieldType.Number,
    is_show_at_front: true,
    order: 45,
    description: "otomatis terisi dari data Warehouse bahan",
    workspace_id: WORKSPACE_ID,
  },

  // Bordir Design Fields (46-48)
  {
    id: CUSTOM_FIELD_IDS.DESAINER_BORDIR,
    name: "Desainer Bordir",
    type: EnumCustomFieldType.Dropdown,
    is_show_at_front: true,
    options: createOptions(["Alvin", "Evan", "Filza"]),
    order: 46,
    description:
      "isi manual oleh SPV Desainer bordir (jika diganti harus SPV yg ganti)",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.CEK_DESAIN_BORDIR,
    name: "Cek Desain Bordir",
    type: EnumCustomFieldType.Checkbox,
    is_show_at_front: true,
    order: 47,
    description: "centang oleh desainer bordir",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.JML_STITCH,
    name: "Jml Stitch",
    type: EnumCustomFieldType.Number,
    is_show_at_front: true,
    order: 48,
    description:
      "isi manual oleh SPV Desainer bordir (jika diganti harus SPV yg ganti)",
    workspace_id: WORKSPACE_ID,
  },

  // Date Fields (49-58)
  {
    id: CUSTOM_FIELD_IDS.WAKTU_LOADING,
    name: "Waktu Loading",
    type: EnumCustomFieldType.Date,
    is_show_at_front: true,
    order: 49,
    description: "",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.SELESAI_CUTTING,
    name: "Selesai Cutting",
    type: EnumCustomFieldType.Date,
    is_show_at_front: true,
    order: 50,
    description: "",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.WAKTU_LOADING_LINE,
    name: "Waktu Loading Line",
    type: EnumCustomFieldType.Date,
    is_show_at_front: true,
    order: 51,
    description: "",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.SELESAI_SEWING,
    name: "Selesai Sewing",
    type: EnumCustomFieldType.Date,
    is_show_at_front: true,
    order: 52,
    description: "",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.SELESAI_QC,
    name: "Selesai QC",
    type: EnumCustomFieldType.Date,
    is_show_at_front: true,
    order: 53,
    description: "",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.WAKTU_SIAP_BORDIR,
    name: "Waktu Siap Bordir",
    type: EnumCustomFieldType.Date,
    is_show_at_front: true,
    order: 54,
    description: "",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.SELESAI_BORDIR,
    name: "Selesai Bordir",
    type: EnumCustomFieldType.Date,
    is_show_at_front: true,
    order: 55,
    description: "",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.SELESAI_DTF,
    name: "Selesai DTF",
    type: EnumCustomFieldType.Date,
    is_show_at_front: true,
    order: 56,
    description: "",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.SELESAI_PACKING,
    name: "Selesai Packing",
    type: EnumCustomFieldType.Date,
    is_show_at_front: true,
    order: 57,
    description: "",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.TGL_SELESAI,
    name: "Tgl Selesai",
    type: EnumCustomFieldType.Date,
    is_show_at_front: true,
    order: 58,
    description: "",
    workspace_id: WORKSPACE_ID,
  },

  // Purchasing - Material Fields (59-67)
  {
    id: CUSTOM_FIELD_IDS.SUPPLIER_BAHAN,
    name: "Suplier Bahan",
    type: EnumCustomFieldType.Dropdown,
    is_show_at_front: true,
    options: createOptions([
      "Simul",
      "Temul",
      "Knitto",
      "Niagara",
      "Altra",
      "Dutex",
      "HM Giwangan",
      "Anugrah Jogja",
      "Anugrah Solo",
      "Ramai Jaya",
      "HM Supeno",
      "Sakura",
      "Toko Kain Soewarno",
      "Weva Textile",
      "Nirwana Tekstil",
      "Kenariatex",
    ]),
    order: 59,
    description: "isi manual oleh purchasing",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.JENIS_BAHAN,
    name: "Jenis Bahan",
    type: EnumCustomFieldType.Dropdown,
    is_show_at_front: true,
    options: createOptions([
      "Lacost Pique Soft 20s",
      "Lacost CVC 20s",
      "Lacost CVC 24s",
      "Cotton Combed 20s",
      "Cotton Combed 24s",
      "Cotton Combed 30s",
      "American Drill",
      "Nagata Drill",
      "Oxford",
      "Textmoda",
      "Ribstop",
      "Taslan Milky",
      "Micro",
      "Adidas",
      "Lotto",
      "Diadora",
      "Canvas Marsoto",
      "Cotton Fleece",
      "PE Fleece",
      "Arrow",
      "Doermill",
    ]),
    order: 60,
    description: "isi manual oleh purchasing",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.WARNA_KAIN,
    name: "Warna Kain",
    type: EnumCustomFieldType.Dropdown,
    is_show_at_front: true,
    options: [],
    order: 61,
    description: "isi manual oleh purchasing",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.JML_ROLL,
    name: "Jml Roll",
    type: EnumCustomFieldType.Number,
    is_show_at_front: true,
    order: 62,
    description: "isi manual oleh purchasing",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.JUMLAH_KM,
    name: "Jumlah KM",
    type: EnumCustomFieldType.Number,
    is_show_at_front: true,
    order: 63,
    description: "isi manual oleh purchasing",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.JUMLAH_RIB,
    name: "Jumlah Rib",
    type: EnumCustomFieldType.Number,
    is_show_at_front: true,
    order: 64,
    description: "isi manual oleh purchasing",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.QTY_BELI_KAIN,
    name: "Qty Beli Kain (kg/m)",
    type: EnumCustomFieldType.Number,
    is_show_at_front: true,
    order: 65,
    description: "isi manual oleh purchasing",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.JENIS_JAHITAN,
    name: "Jenis Jahitan",
    type: EnumCustomFieldType.Dropdown,
    is_show_at_front: true,
    options: createOptions([
      "Polo Shirt",
      "Kaos Oblong",
      "Kemeja",
      "Rompi",
      "Jaket",
      "Celana Training",
      "Apron",
      "Jersey",
      "Hoodie",
    ]),
    order: 66,
    description: "isi manual oleh purchasing",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.TGL_DITERIMA,
    name: "Tgl Diterima",
    type: EnumCustomFieldType.Date,
    is_show_at_front: true,
    order: 67,
    description: "otomatis terisi ketika complete / diterima",
    workspace_id: WORKSPACE_ID,
  },

  // Purchasing - Suppliers (68-71)
  {
    id: CUSTOM_FIELD_IDS.SUPPLIER_KM_CUSTOM,
    name: "Suplier KM Custom",
    type: EnumCustomFieldType.Dropdown,
    is_show_at_front: true,
    options: createOptions([
      "Istana Krah",
      "Rukiat",
      "Rifqy Jaya",
      "Krah Manset Yon",
    ]),
    order: 68,
    description: "isi manual oleh purchasing",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.SUPPLIER_ACC,
    name: "Suplier ACC",
    type: EnumCustomFieldType.Dropdown,
    is_show_at_front: true,
    options: createOptions([
      "GML",
      "Sri Indah",
      "Kurniasolo",
      "Nikimurah",
      "Jago",
      "Gracia Indah",
      "Narwastu",
      "Maliqa",
      "Tokped",
      "Shopee",
      "Toko Sepuluh",
    ]),
    order: 69,
    description: "isi manual oleh purchasing",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.SUPPLIER_SPAREPART,
    name: "Suplier Sparepart",
    type: EnumCustomFieldType.Dropdown,
    is_show_at_front: true,
    options: createOptions(["Obor", "Singer", "Indohose"]),
    order: 70,
    description: "isi manual oleh purchasing",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.SUPPLIER_PERLENGKAPAN,
    name: "Suplier Perlengkapan",
    type: EnumCustomFieldType.Dropdown,
    is_show_at_front: true,
    options: createOptions([
      "Toko 60 Tajem",
      "Sumberjaya Plastik",
      "Liman Simanjuntak",
      "Polyta",
      "Puspitamas",
      "Toko Elektronik",
      "Mitra Abadi (seturan)",
      "CV Bandung",
      "DOT Print",
      "Tokopedia",
      "Putra Mataram",
    ]),
    order: 71,
    description: "isi manual oleh purchasing",
    workspace_id: WORKSPACE_ID,
  },

  // Delivery Management (72-74)
  {
    id: CUSTOM_FIELD_IDS.ASAL,
    name: "Asal",
    type: EnumCustomFieldType.Dropdown,
    is_show_at_front: true,
    options: createOptions([
      "PBR",
      "WBT",
      "KBT",
      "KLT",
      "MGW",
      "SLO",
      "HM",
      "Niagara",
      "Simul",
      "Kalog",
      "Anugrah Cokro",
      "Anugrah Kolonel",
      "Raja Topi",
      "Ace Cokro",
      "UD Bandung",
      "Singer",
      "Maxima",
      "Gracia",
      "Narwastu",
      "Kurniasolo",
      "Sumber Jaya",
      "Toko 60 Tajem",
      "Toko Soewarno",
      "Toko Merah",
      "Puspita Mas",
      "Ramau Jaya",
      "Toko Jago",
      "Mitra Abadi",
      "Otramus",
      "Metro Kampus",
      "Liman Simanjuntak",
      "HM Supeno",
      "DOT Print",
      "Maliqa",
      "Pamela",
      "Knitto",
      "CV Bandung",
      "CV Sakura",
      "Putra Mataram",
      "Nirwana Tekstil",
      "Ortindo",
      "Young Computer",
      "Rizky Printing",
      "Kertas Putih",
      "Go Jersey",
      "ELS ID",
      "Toko 96",
      "Jogja Bordir",
      "Paxel",
      "Printwar",
    ]),
    order: 72,
    description:
      "isi manual oleh yang input data delivery (siapapun yg berwenang)",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.TUJUAN,
    name: "Tujuan",
    type: EnumCustomFieldType.Dropdown,
    is_show_at_front: true,
    options: createOptions([
      "PBR",
      "WBT",
      "KBT",
      "KLT",
      "MGW",
      "SLO",
      "Customer",
      "Shopee",
      "Sentral",
      "Sicepat",
      "Kalog",
      "Simul",
      "Rizky Printing",
      "JNE",
      "Otramus",
      "Go Jersey",
      "Singer",
      "Young Computer",
      "Travel",
      "Eks Margorejo",
      "Niagara",
      "Gunung Harta",
      "DOT Print",
      "Tidak ada? Tulis di Ket",
    ]),
    order: 73,
    description:
      "isi manual oleh yang input data delivery (siapapun yg berwenang)",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.KURIR,
    name: "Kurir",
    type: EnumCustomFieldType.Dropdown,
    is_show_at_front: true,
    options: createOptions([
      "Alex",
      "Zoga",
      "Heru",
      "Gosend",
      "Erma",
      "Makmur",
      "Travel",
    ]),
    order: 74,
    description: "isi manual oleh SPV Kurir",
    workspace_id: WORKSPACE_ID,
  },

  // Operator Bordir Fields (75-83)
  {
    id: CUSTOM_FIELD_IDS.OPERATOR,
    name: "Operator",
    type: EnumCustomFieldType.Dropdown,
    is_show_at_front: true,
    options: createOptions([
      "Adi Suryo",
      "Dheva",
      "Lilik",
      "Roni",
      "Ajek",
      "Fikri",
      "Redy",
      "Haikal",
      "Okta",
      "Dzaki",
      "Panji",
    ]),
    order: 75,
    description: "isi manual oleh operator bordir",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.NAMA_CUSTOMER_OPERATOR,
    name: "Nama Customer",
    type: EnumCustomFieldType.Dropdown,
    is_show_at_front: true,
    options: createOptions([
      "WBT",
      "KBT",
      "KLT",
      "MGW",
      "SLO",
      "IND",
      "PLO",
      "End User",
      "Migunani",
    ]),
    order: 76,
    description: "isi manual oleh operator bordir",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.MESIN_BORDIR_OPERATOR,
    name: "Mesin Bordir Operator",
    type: EnumCustomFieldType.Dropdown,
    is_show_at_front: true,
    options: createOptions(["12 Head", "6 Head", "4 Head", "2 Head"]),
    order: 77,
    description: "isi manual oleh operator bordir",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.JENIS_ORDER,
    name: "Jenis Order",
    type: EnumCustomFieldType.Dropdown,
    is_show_at_front: true,
    options: createOptions(["New Order", "Kekurangan", "Reject Kain"]),
    order: 78,
    description: "isi manual oleh operator bordir",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.NAMA_FILE,
    name: "Nama File",
    type: EnumCustomFieldType.Text,
    is_show_at_front: true,
    order: 79,
    description: "isi manual oleh operator bordir",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.DESAINER_OPERATOR,
    name: "Desainer Operator",
    type: EnumCustomFieldType.Dropdown,
    is_show_at_front: true,
    options: createOptions(["Alvin", "Evan", "Filza"]),
    order: 80,
    description: "isi manual oleh operator bordir",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.STITCH,
    name: "Stitch",
    type: EnumCustomFieldType.Number,
    is_show_at_front: true,
    order: 81,
    description: "isi manual oleh operator bordir",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.JUMLAH_BORDIR,
    name: "Jumlah Bordir",
    type: EnumCustomFieldType.Number,
    is_show_at_front: true,
    order: 82,
    description: "isi manual oleh operator bordir",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.TOTAL_STITCH,
    name: "Total Stitch",
    type: EnumCustomFieldType.Number,
    is_show_at_front: true,
    order: 83,
    description: "hitungan otomatis Stitch * Jml Bordir",
    workspace_id: WORKSPACE_ID,
  },

  // Finishing Bordir Fields (84-87)
  {
    id: CUSTOM_FIELD_IDS.FINISHER,
    name: "Finisher",
    type: EnumCustomFieldType.Dropdown,
    is_show_at_front: true,
    options: createOptions(["Alef", "Firza"]),
    order: 84,
    description: "isi manual oleh finishing bordir",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.NAMA_CUSTOMER_FINISHING,
    name: "Nama Customer Finishing",
    type: EnumCustomFieldType.Dropdown,
    is_show_at_front: true,
    options: createOptions([
      "WBT",
      "KBT",
      "KLT",
      "MGW",
      "SLO",
      "IND",
      "PLO",
      "End User",
      "Migunani",
    ]),
    order: 85,
    description: "isi manual oleh finishing bordir",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.NAMA_FILE_FINISHING,
    name: "Nama File Finishing",
    type: EnumCustomFieldType.Text,
    is_show_at_front: true,
    order: 86,
    description: "isi manual oleh finishing bordir",
    workspace_id: WORKSPACE_ID,
  },
  {
    id: CUSTOM_FIELD_IDS.JUMLAH_BORDIR_FINISHING,
    name: "Jumlah Bordir Finishing",
    type: EnumCustomFieldType.Number,
    is_show_at_front: true,
    order: 87,
    description: "isi manual oleh finishing bordir",
    workspace_id: WORKSPACE_ID,
  },
];

export default {
  up: async (queryInterface: QueryInterface) => {
    // First, delete any existing custom fields with the same IDs to avoid conflicts
    await queryInterface.bulkDelete("custom_field", {
      id: Object.values(CUSTOM_FIELD_IDS),
    });

    // Then insert all custom fields
    await queryInterface.bulkInsert(
      "custom_field",
      customFields.map((field) => ({
        ...field,
        source: EnumCustomFieldSource.Custom,
        options: JSON.stringify(field.options || []),
        created_at: new Date(),
        updated_at: new Date(),
      }))
    );
  },

  down: async (queryInterface: QueryInterface) => {
    // Delete all custom fields
    await queryInterface.bulkDelete("custom_field", {
      id: Object.values(CUSTOM_FIELD_IDS),
    });
  },
};
